@startgantt
Project starts 2023-06-01

[Project planning] lasts 1 days and is colored in purple
[Analysis] starts at [Project planning]'s end and lasts 4 day and is colored in green
[Design] starts  at [Project planning]'s end and lasts 6 day and is colored in yellow
[Implementation] starts D+4 and lasts 5 day and is colored in red
[Testing] starts D+6 and lasts 6 day and is colored in orange
[Report] starts D+7 and lasts 7 day and is colored in magenta
[Code freeze] happens at [Implementation]'s end and is colored in red
[Project submission] happens at [Report]'s end and is colored in magenta

@endgantt