@startgantt
[Prototype design] lasts 21 days
[Test prototype] lasts 10 days
-- All tasks --
[Requirements (1 day)] lasts 1 day
[T2 (5 days)] lasts 5 days
[T2 (5 days)] ends D+6

[T3 (1 week)] lasts 1 week
[T4 (1 week and 4 days)] lasts 1 week and 4 days
[T5 (2 weeks)] lasts 2 weeks
@endgantt