@startuml
left to right direction
skinparam packageStyle rectangle
actor player

rectangle Client {
  player -- (Play game)

  (Play game) .> (Single player) : <<include>>
  (save/load game) .> (Play game)  : <<extends>>
  }

rectangle Server {
    (Play game) .-> (Multi player) : <<include>>
    (Multi player) .-> (join game) : <<include>>
    (Multi player) .-> (host game) : <<include>>
}



@enduml