@startuml
left to right direction
skinparam packageStyle rectangle
actor player
'actor player2

rectangle PlayGame {
  player -- (PlayGame)
  (PlayGame) .> (new game) : <<include>>
  (load game) .> (PlayGame) #blue;line.dashed;text:blue : <<extends>>
  (PlayGame) .> (join game) : <<include>>
  (save game) .> (PlayGame) #blue;line.dashed;text:blue : <<extends>>
  '(PlayGame) -- player2
}

@enduml